name: Deploy to InfinityFree

on:
  push:
    branches:
      - master   # or main, whatever your default branch is

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/README.md
            **/fiveserver.config.js